name: ASP.NET Web API Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0

    - name: Build ASP.NET Web API
      run: dotnet build ./API/API.csproj

    - name: Publish ASP.NET Web API
      run: dotnet publish <path-to-your-project> --configuration Release --output ${{ github.workspace }}/publish

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: '${{ github.workspace }}/publish/*'
        target: '/var/www/nginx/wwwroot/'

    - name: SSH into server and restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: 'sudo systemctl restart nginx'
